Repository andela/northstar-backend, pull requests merged in 2019-08, with the labels that each got.

#1 #167727445 Set up Dotenv
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/index.js
Labels: Ready for review

#7 #167727449 Set up Docker For Back End
  .babelrc
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  docker-compose.yaml
  package.json
  src/index.js
Labels: Reviewed

#8 #167727442 Integrate houndCI with readme badge
  .hound.yml
  README.md
Labels: Ready for review

#14 #167727440 Setup Sequelize
  .env.example
  .eslintrc.json
  .gitignore
  .hound.yml
  .sequelizerc
  package-lock.json
  package.json
  src/config/db.config.js
  src/config/index.js
  src/config/passport.js
  src/database/config.js
  src/database/migrations/20190819194857-create-user.js
  src/database/migrations/20190820071904-create-department.js
  src/database/models/department.js
  src/database/models/index.js
  src/database/models/user.js
Labels: Raedy

#13 #167727443 Setup travisci with readme badge
  .travis.yml
Labels: Ready for review

#15 #168024327 Create necessary database tables
  .sequelizerc
  src/config/index.js
  src/config/passport.js
  src/db/config/db.config.js
  src/db/migrations/20190819194857-create-user.js
  src/db/migrations/20190820071904-create-department.js
  src/db/migrations/20190821140128-create-suppliers.js
  src/db/migrations/20190821140753-create-facilities.js
  src/db/migrations/20190821142413-create-likes.js
  src/db/migrations/20190821143206-create-rooms.js
  src/db/migrations/20190821144025-create-amenities.js
  src/db/migrations/20190821144633-create-feedback.js
  src/db/migrations/20190821153031-create-booking.js
  src/db/migrations/20190821153817-create-rating.js
  src/db/migrations/20190821154724-create-trip.js
  src/db/migrations/20190821160011-create-comment.js
  src/db/migrations/20190821160830-create-notification.js
  src/db/models/amenity.js
  src/db/models/booking.js
  src/db/models/comment.js
  src/db/models/department.js
  src/db/models/facility.js
  src/db/models/feedback.js
  src/db/models/index.js
  src/db/models/like.js
  src/db/models/notification.js
  src/db/models/rating.js
  src/db/models/room.js
  src/db/models/supplier.js
  src/db/models/trip.js
  src/db/models/user.js
Labels: Ready for review

#30 #168134583 Update database
  src/db/migrations/20190819194857-create-user.js
  src/db/migrations/20190820071904-create-department.js
  src/db/migrations/20190821140128-create-suppliers.js
  src/db/migrations/20190821140753-create-facilities.js
  src/db/migrations/20190821142413-create-likes.js
  src/db/migrations/20190821143206-create-rooms.js
  src/db/migrations/20190821144025-create-amenities.js
  src/db/migrations/20190821144633-create-feedback.js
  src/db/migrations/20190821153031-create-booking.js
  src/db/migrations/20190821153817-create-rating.js
  src/db/migrations/20190821154724-create-requests.js
  src/db/migrations/20190821160011-create-comment.js
  src/db/migrations/20190821160830-create-notification.js
  src/db/models/amenity.js
  src/db/models/booking.js
  src/db/models/comment.js
  src/db/models/department.js
  src/db/models/facility.js
  src/db/models/feedback.js
  src/db/models/like.js
  src/db/models/notification.js
  src/db/models/rating.js
  src/db/models/request.js
  src/db/models/room.js
  src/db/models/supplier.js
  src/db/models/user.js
Labels: Ready for review

#29 #167727454 Implement In-app Signin
  .eslintrc.json
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/controllers/users.js
  src/index.js
  src/middlewares/auth.js
  src/middlewares/user.middleware.js
  src/models/User.js
  src/routes/api/auth.router.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/services/email.service.js
  src/services/jwt.service.js
  src/services/tokenGenerator.js
  src/test/signin.test.js
  src/test/signup.test.js
  src/utils/response.utils.js
  src/utils/user.js
  src/utils/user.utils.js
  swagger.json
Labels: Raedy

#31 #168174737 Seed The Database
  .DS_Store
  .eslintrc.json
  .gitignore
  .nycrc.json
  .travis.yml
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/controllers/users.js
  src/db/config/db.config.js
  src/db/migrations/20190819194857-create-user.js
  src/db/migrations/20190821153031-create-booking.js
  src/db/migrations/20190821154724-create-requests.js
  src/db/migrations/20190821160011-create-comment.js
  src/db/models/booking.js
  src/db/models/request.js
  src/db/models/user.js
  src/db/seeders/20190828065701-users-seeder.js
  src/db/seeders/20190828065719-facilities-seeder.js
  src/db/seeders/20190828065748-amenities-seeder.js
  src/db/seeders/20190828065803-rooms-seeder.js
  src/db/seeders/20190828065817-likes-seeder.js
  src/db/seeders/20190828065822-ratings-seeder.js
  src/db/seeders/20190828065829-feedback-seeder.js
  src/db/seeders/20190828065846-bookings-seeder.js
  src/db/seeders/20190828065852-comments-seeder.js
  src/db/seeders/20190828065926-notifications-seeder.js
  src/index.js
  src/logs/winston.js
  src/middlewares/auth.js
  src/middlewares/user.middleware.js
  src/services/email.service.js
  src/services/jwt.service.js
  src/services/tokenGenerator.js
  src/test/signup.test.js
  src/utils/user.utils.js
Labels: Ready for review

#33 #168191152 fix test script
  package.json
Labels: Raedy, Reviewed
