Repository andela/northstar-backend, pull requests merged in 2019-09, with the labels that each got.

#21 #167727463 Integrate the Requests Table
  .babelrc
  .env.example
  .eslintignore
  .eslintrc.json
  .mocharc.json
  .travis.yml
  Dockerfile
  package-lock.json
  package.json
  src/controllers/request.controller.js
  src/controllers/user.controller.js
  src/index.js
  src/middlewares/auth.js
  src/middlewares/auth.middleware.js
  src/routes/api/auth.router.js
  src/routes/api/index.js
  src/routes/api/index.router.js
  src/routes/api/requests.router.js
  src/routes/index.js
  src/test/index.test.js
  src/test/request.test.js
  src/test/requests.test.js
  src/test/signup.test.js
  src/utils/response.utils.js
Labels: => 1, Reviewed

#35 #167727470 User should be able to delete his/her comment
  package-lock.json
  package.json
  src/controllers/comment.controller.js
  src/db/migrations/20190821160011-create-comment.js
  src/db/models/comment.js
  src/middlewares/auth.js
  src/middlewares/comment.middleware.js
  src/routes/api/comment.router.js
  src/routes/api/index.js
  src/routes/index.js
  src/test/comment.js
  src/utils/comment.util.js
  swagger.json
Labels: Ready for review

#43 #167727464 User role settings
  package.json
  src/controllers/request.controller.js
  src/controllers/user.controller.js
  src/index.js
  src/middlewares/auth.middleware.js
  src/middlewares/jwtAuth.js
  src/middlewares/user.middleware.js
  src/routes/api/index.router.js
  src/routes/api/user.router.js
  src/routes/index.js
  src/test/user/role.test.js
  src/utils/user.utils.js
  src/validation/user/role.validation.js
Labels: Raedy, Reviewed

#39 #167727459 Make One-Way Trip Requests
  .hound.yml
  README.md
  package-lock.json
  src/controllers/request.controller.js
  src/db/seeders/20190828065719-facilities-seeder.js
  src/db/seeders/20190828065817-likes-seeder.js
  src/db/seeders/20190828065822-ratings-seeder.js
  src/db/seeders/20190828065829-feedback-seeder.js
  src/db/seeders/20190828065846-bookings-seeder.js
  src/routes/api/requests.router.js
  src/test/request.test.js
  src/utils/helpers.utils.js
  src/utils/regexen.utils.js
  src/utils/response.utils.js
  src/validation/index.js
Labels: Reviewed

#42 #167727455 Implement Social Signin
  .env.example
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/index.js
  src/middlewares/social-mock.middleware.js
  src/routes/api/auth.router.js
  src/test/signin.test.js
  src/test/social-auth.test.js
  src/utils/user.utils.js
  src/validation/passport.config.js
  swagger.json
Labels: Raedy

#49 #167727461 Users Can Make Multi City Request
  package.json
  src/controllers/request.controller.js
  src/routes/api/requests.router.js
  src/test/request/multiCity.test.js
  src/test/request/request.test.js
Labels: Reviewed

#45 #168250510 Get comments for a request
  src/controllers/comment.controller.js
  src/middlewares/comment.middleware.js
  src/routes/api/comment.router.js
  src/test/comment.js
  src/test/comment.test.js
  src/utils/comment.util.js
  swagger.json
Labels: Raedy, Reviewed

#54 #167727477 A Travel Admin can Create Accomodation Facilities And Rooms
  src/controllers/facilities.controller.js
  src/controllers/request.controller.js
  src/db/models/like.js
  src/db/models/request.js
  src/db/models/room.js
  src/db/seeders/20190828065701-users-seeder.js
  src/index.js
  src/middlewares/auth.js
  src/middlewares/facilities.middleware.js
  src/routes/api/facilities.router.js
  src/routes/api/index.js
  src/routes/api/requests.router.js
  src/routes/index.js
  src/test/auth.test.js
  src/test/facilities/facilities.test.js
  src/test/facilities/rooms.test.js
  src/test/request/request.test.js
  src/test/signup.test.js
  src/utils/facility.utils.js
  src/utils/user.utils.js
  src/validation/facilities/facilities.validation.js
  src/validation/facilities/rooms.validation.js
Labels: Reviewed

#55 #168250634 Get All Facilities
  src/controllers/facilities.controller.js
  src/db/migrations/20190821142413-create-likes.js
  src/logs/app1.log
  src/routes/api/facilities.router.js
  src/test/facilities/facilities.test.js
  src/validation/facilities/facilities.validation.js
  swagger.json
Labels: In review

#32 #167727460 Users should be able to make Return trip
  .gitignore
  package-lock.json
  src/controllers/request.controller.js
  src/controllers/user.controller.js
  src/middlewares/auth.middleware.js
  src/middlewares/jwtAuth.js
  src/routes/api/index.router.js
  src/test/comment.test.js
  src/test/request/request.test.js
  src/utils/helpers.utils.js
  src/validation/index.js
Labels: Ready for review

#38 #167727458 Update profile
  src/controllers/user.controller.js
  src/index.js
  src/middlewares/profile.middleware.js
  src/middlewares/sanitizer.middleware.js
  src/routes/api/requests.router.js
  src/routes/api/user.router.js
  src/test/app.test.js
  src/test/jwtAuth.js
  src/test/user.test.js
  src/test/user.utils.test.js
  src/utils/user.utils.js
  src/validation/profile.validation.js
  swagger.json
Labels: Ready for review

#44 #166214115 user should reset password
  src/controllers/user.controller.js
  src/routes/api/auth.router.js
  src/services/email.service.js
  src/services/jwt.service.js
  src/test/signup.test.js
  swagger.json
Labels: Raedy, Reviewed

#56 #168250754 Fetch Single Travel Request
  src/controllers/request.controller.js
  src/db/seeders/20190828065701-users-seeder.js
  src/db/seeders/20190828065852-comments-seeder.js
  src/routes/api/requests.router.js
  src/test/request/get-single.test.js
  src/test/request/request.test.js
  src/test/signin.test.js
  src/test/social-auth.test.js
  src/utils/response.utils.js
  swagger.json
Labels: Ready for review

#51 #168250881 Get All Ratings
  src/controllers/rating.controller.js
  src/db/seeders/20190828065719-facilities-seeder.js
  src/db/seeders/20190828065829-feedback-seeder.js
  src/routes/api/index.js
  src/routes/api/rating.router.js
  src/routes/index.js
  src/test/rating.test.js
  src/validation/index.js
Labels: Ready for review

#65 #168382828 Mend Broken Tests on Develop
  src/db/seeders/20190828065701-users-seeder.js
  src/test/comment/postComments.test.js
Labels: Ready for review

#50 #168250889 Get All Feedback
  src/controllers/feedback.controller.js
  src/db/models/feedback.js
  src/middlewares/auth.middleware.js
  src/routes/api/feedback.router.js
  src/routes/index.js
  src/test/feedback.test.js
  swagger.json
Labels: Reviewed

#63 feature(request): implement search on travel requests
  src/controllers/request.controller.js
  src/db/migrations/20190821154724-create-requests.js
  src/db/models/request.js
  src/db/seeders/20190828065701-users-seeder.js
  src/db/seeders/20190828065852-comments-seeder.js
  src/middlewares/requests.middleware.js
  src/routes/api/requests.router.js
  src/test/request/request.test.js
  src/test/request/search-request.test.js
  src/test/signup.test.js
  src/test/social-auth.test.js
  src/utils/request.utils.js
  src/utils/response.utils.js
  swagger.json
Labels: Ready for review

#78 #168477780 Add "facility_id" To "bookings" Table
  package.json
  src/controllers/facilities.controller.js
  src/controllers/rating_feedback.controller.js
  src/controllers/request.controller.js
  src/db/migrations/20190821153031-create-booking.js
  src/db/migrations/20190909225417-create-check_in.js
  src/db/models/booking.js
  src/db/models/check_in.js
  src/db/seeders/20190828065846-bookings-seeder.js
  src/db/seeders/20190828065852-comments-seeder.js
  src/db/seeders/20190909231921-check_ins-seeder.js
  src/middlewares/facilities.middleware.js
  src/test/app.test.js
  src/test/auth.test.js
  src/test/bookings/checkin.test.js
  src/test/comment.test.js
  src/test/comment/post-comments.test.js
  src/test/facilities/booking.test.js
  src/test/facilities/facilities.test.js
  src/test/facilities/likes.test.js
  src/test/facilities/rooms.test.js
  src/test/index.test.js
  src/test/rating_feedback/feedback.test.js
  src/test/rating_feedback/rating.test.js
  src/test/request/approve-request.js
  src/test/request/get-single.test.js
  src/test/request/multi-city.test.js
  src/test/request/multiCity.test.js
  src/test/request/request.test.js
  src/test/request/search-request.test.js
  src/test/retrieve-profile.test.js
  src/test/signup.test.js
  src/test/user.test.js
  src/test/user/getmanagers.test.js
  src/test/user/role.test.js
  src/test/user/verify-user.test.js
Labels: Ready

#68 #168255235 Bookings and Requests History
  src/controllers/request.controller.js
  src/db/seeders/20190828065852-comments-seeder.js
  src/routes/api/requests.router.js
  src/test/request/history.test.js
  swagger.json
Labels: Ready, Reviewed
